// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GmX {
    
    
    public partial class VolumeSliderPopup {
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.VScale vscale1;
        
        private Gtk.EventBox eventbox1;
        
        private Gtk.Image image1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GmX.VolumeSliderPopup
            this.Name = "GmX.VolumeSliderPopup";
            this.Title = "";
            this.TypeHint = ((Gdk.WindowTypeHint)(4));
            this.WindowPosition = ((Gtk.WindowPosition)(2));
            this.Decorated = false;
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            // Container child GmX.VolumeSliderPopup.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.vscale1 = new Gtk.VScale(null);
            this.vscale1.CanFocus = true;
            this.vscale1.Name = "vscale1";
            this.vscale1.Inverted = true;
            this.vscale1.Adjustment.Upper = 100;
            this.vscale1.Adjustment.PageIncrement = 10;
            this.vscale1.Adjustment.StepIncrement = 1;
            this.vscale1.Adjustment.Value = 100;
            this.vscale1.DrawValue = true;
            this.vscale1.Digits = 0;
            this.vscale1.ValuePos = ((Gtk.PositionType)(2));
            this.vbox1.Add(this.vscale1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.vscale1]));
            w1.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.eventbox1 = new Gtk.EventBox();
            this.eventbox1.Name = "eventbox1";
            // Container child eventbox1.Gtk.Container+ContainerChild
            this.image1 = new Gtk.Image();
            this.image1.Name = "image1";
            this.image1.Ypad = 5;
            this.image1.Pixbuf = Gdk.Pixbuf.LoadFromResource("audio-volume-high.png");
            this.eventbox1.Add(this.image1);
            this.vbox1.Add(this.eventbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.eventbox1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 29;
            this.DefaultHeight = 300;
            this.Show();
            this.vscale1.ValueChanged += new System.EventHandler(this.OnVscale1ValueChanged);
            this.eventbox1.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnEventbox1ButtonReleaseEvent);
        }
    }
}
