// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action EditAction;
    
    private Gtk.Action ViewAction;
    
    private Gtk.Action OptionsAction;
    
    private Gtk.Action LibraryAction;
    
    private Gtk.Action goBackAction;
    
    private Gtk.Action goForwardAction;
    
    private Gtk.Action goBackAction1;
    
    private Gtk.Action goForwardAction1;
    
    private Gtk.Action mediaPreviousAction;
    
    private Gtk.Action mediaNextAction;
    
    private Gtk.Action mediaPlayAction;
    
    private Gtk.Action mediaStopAction;
    
    private Gtk.ToggleAction mediaPauseAction;
    
    private Gtk.Action mediaRewindAction;
    
    private Gtk.Action mediaForwardAction;
    
    private Gtk.Action OpenAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action AddFileToLibraryAction;
    
    private Gtk.Action AddDirectoryToLibraryAction;
    
    private Gtk.Action AddFileToPlaylistAction;
    
    private Gtk.Action AddDirectoryToPlaylistAction;
    
    private Gtk.Action addMediaButton;
    
    private Gtk.Action removeAction;
    
    private Gtk.Action sortAscendingAction;
    
    private Gtk.Action sortDescendingAction;
    
    private Gtk.Action clearAction;
    
    private Gtk.ToggleAction stockVolumeAction;
    
    private Gtk.ToggleAction stockPlaylistAction;
    
    private Gtk.Action Action;
    
    private Gtk.Action addAction1;
    
    private Gtk.Action stockVolumeAction1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Toolbar toolbar4;
    
    private Gtk.Toolbar toolbar3;
    
    private Gtk.Toolbar toolbar2;
    
    private Gtk.HBox hbox4;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox5;
    
    private Gtk.VBox vbox3;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label countUpTimeLabel;
    
    private Gtk.VBox vbox13;
    
    private Gtk.Label artistLabel;
    
    private Gtk.Label trackLabel;
    
    private Gtk.Label albumLabel;
    
    private Gtk.Label countDownTimeLabel;
    
    private Gtk.HBox hbox1;
    
    private Gtk.HScale songProgressBar;
    
    private Gtk.HBox hbox8;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.VPaned vpaned1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.NodeView nodeview2;
    
    private Gtk.ScrolledWindow GtkScrolledWindow2;
    
    private Gtk.NodeView nodeview3;
    
    private Gtk.HPaned hpaned2;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.NodeView nodeview1;
    
    private Gtk.VBox vbox1;
    
    private Gtk.Image AlbumArtIcon;
    
    private Gtk.Label label1;
    
    private Gtk.Label label2;
    
    private Gtk.Label label3;
    
    private Gtk.HBox hbox9;
    
    private Gtk.VBox vbox7;
    
    private Gtk.Label spacer2Label;
    
    private Gtk.VScale vscale2;
    
    private Gtk.VScale vscale3;
    
    private Gtk.VScale vscale4;
    
    private Gtk.VScale vscale5;
    
    private Gtk.VScale vscale6;
    
    private Gtk.VScale vscale7;
    
    private Gtk.VScale vscale8;
    
    private Gtk.VScale vscale9;
    
    private Gtk.VBox vbox8;
    
    private Gtk.Label spacer1Label;
    
    private Gtk.HBox hbox6;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Label newSongLabel;
    
    private Gtk.HBox hbox14;
    
    private Gtk.Label newSongLocationLabel;
    
    private Gtk.Label tracksAddedLabel;
    
    private Gtk.HBox hbox13;
    
    private Gtk.ProgressBar songsAddedProgressBar;
    
    private Gtk.Button button1;
    
    private Gtk.HBox hbox10;
    
    private Gtk.VBox vbox9;
    
    private Gtk.Label label19;
    
    private Gtk.Label label17;
    
    private Gtk.Label label18;
    
    private Gtk.VBox vbox10;
    
    private Gtk.HScale hscale2;
    
    private Gtk.HScale hscale3;
    
    private Gtk.HScale hscale4;
    
    private Gtk.VBox vbox11;
    
    private Gtk.HBox hbox11;
    
    private Gtk.VBox vbox12;
    
    private Gtk.HBox hbox12;
    
    private Gtk.CheckButton checkbutton2;
    
    private Gtk.Toolbar toolbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.EditAction = new Gtk.Action("EditAction", Mono.Unix.Catalog.GetString("Edit"), null, null);
        this.EditAction.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
        w1.Add(this.EditAction, null);
        this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("View"), null, null);
        this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
        w1.Add(this.ViewAction, null);
        this.OptionsAction = new Gtk.Action("OptionsAction", Mono.Unix.Catalog.GetString("Options"), null, null);
        this.OptionsAction.ShortLabel = Mono.Unix.Catalog.GetString("Options");
        w1.Add(this.OptionsAction, null);
        this.LibraryAction = new Gtk.Action("LibraryAction", Mono.Unix.Catalog.GetString("Library"), null, null);
        this.LibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.LibraryAction, null);
        this.goBackAction = new Gtk.Action("goBackAction", null, null, "gtk-go-back");
        w1.Add(this.goBackAction, null);
        this.goForwardAction = new Gtk.Action("goForwardAction", null, null, "gtk-go-forward");
        w1.Add(this.goForwardAction, null);
        this.goBackAction1 = new Gtk.Action("goBackAction1", null, null, "gtk-go-back");
        w1.Add(this.goBackAction1, null);
        this.goForwardAction1 = new Gtk.Action("goForwardAction1", null, null, "gtk-go-forward");
        w1.Add(this.goForwardAction1, null);
        this.mediaPreviousAction = new Gtk.Action("mediaPreviousAction", null, null, "gtk-media-previous");
        w1.Add(this.mediaPreviousAction, null);
        this.mediaNextAction = new Gtk.Action("mediaNextAction", null, null, "gtk-media-next");
        w1.Add(this.mediaNextAction, null);
        this.mediaPlayAction = new Gtk.Action("mediaPlayAction", null, null, "gtk-media-play");
        w1.Add(this.mediaPlayAction, null);
        this.mediaStopAction = new Gtk.Action("mediaStopAction", null, null, "gtk-media-stop");
        w1.Add(this.mediaStopAction, null);
        this.mediaPauseAction = new Gtk.ToggleAction("mediaPauseAction", null, null, "gtk-media-pause");
        w1.Add(this.mediaPauseAction, null);
        this.mediaRewindAction = new Gtk.Action("mediaRewindAction", null, null, "gtk-media-rewind");
        w1.Add(this.mediaRewindAction, null);
        this.mediaForwardAction = new Gtk.Action("mediaForwardAction", null, null, "gtk-media-forward");
        w1.Add(this.mediaForwardAction, null);
        this.OpenAction = new Gtk.Action("OpenAction", Mono.Unix.Catalog.GetString("Open"), null, null);
        this.OpenAction.ShortLabel = Mono.Unix.Catalog.GetString("Open");
        w1.Add(this.OpenAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.AddFileToLibraryAction = new Gtk.Action("AddFileToLibraryAction", Mono.Unix.Catalog.GetString("Add File To Library"), null, "gtk-file");
        this.AddFileToLibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Add File");
        w1.Add(this.AddFileToLibraryAction, null);
        this.AddDirectoryToLibraryAction = new Gtk.Action("AddDirectoryToLibraryAction", Mono.Unix.Catalog.GetString("Add Directory To Library"), null, "gtk-directory");
        this.AddDirectoryToLibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Add Directory");
        w1.Add(this.AddDirectoryToLibraryAction, null);
        this.AddFileToPlaylistAction = new Gtk.Action("AddFileToPlaylistAction", Mono.Unix.Catalog.GetString("Add File to Playlist"), null, "gtk-file");
        this.AddFileToPlaylistAction.ShortLabel = Mono.Unix.Catalog.GetString("Add File to Playlist");
        w1.Add(this.AddFileToPlaylistAction, null);
        this.AddDirectoryToPlaylistAction = new Gtk.Action("AddDirectoryToPlaylistAction", Mono.Unix.Catalog.GetString("Add Directory to Playlist"), null, "gtk-directory");
        this.AddDirectoryToPlaylistAction.ShortLabel = Mono.Unix.Catalog.GetString("Add Directory to Playlist");
        w1.Add(this.AddDirectoryToPlaylistAction, null);
        this.addMediaButton = new Gtk.Action("addMediaButton", null, null, "gtk-add");
        w1.Add(this.addMediaButton, null);
        this.removeAction = new Gtk.Action("removeAction", null, null, "gtk-remove");
        w1.Add(this.removeAction, null);
        this.sortAscendingAction = new Gtk.Action("sortAscendingAction", null, null, "gtk-sort-ascending");
        w1.Add(this.sortAscendingAction, null);
        this.sortDescendingAction = new Gtk.Action("sortDescendingAction", null, null, "gtk-sort-descending");
        w1.Add(this.sortDescendingAction, null);
        this.clearAction = new Gtk.Action("clearAction", null, null, "gtk-clear");
        w1.Add(this.clearAction, null);
        this.stockVolumeAction = new Gtk.ToggleAction("stockVolumeAction", null, null, "stock-volume");
        w1.Add(this.stockVolumeAction, null);
        this.stockPlaylistAction = new Gtk.ToggleAction("stockPlaylistAction", null, null, "stock-playlist");
        w1.Add(this.stockPlaylistAction, null);
        this.Action = new Gtk.Action("Action", null, null, null);
        w1.Add(this.Action, null);
        this.addAction1 = new Gtk.Action("addAction1", null, null, "gtk-add");
        w1.Add(this.addAction1, null);
        this.stockVolumeAction1 = new Gtk.Action("stockVolumeAction1", null, null, "stock-volume");
        w1.Add(this.stockVolumeAction1, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("GmX");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        // Container child vbox2.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menu name='OpenAction' action='OpenAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='ViewAction' action='ViewAction'/><menu name='OptionsAction' action='OptionsAction'/><menu name='LibraryAction' action='LibraryAction'><menuitem name='AddFileToLibraryAction' action='AddFileToLibraryAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox2.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        // Container child hbox3.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar4'/></ui>");
        this.toolbar4 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
        this.toolbar4.Name = "toolbar4";
        this.toolbar4.ShowArrow = false;
        this.toolbar4.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar4.IconSize = ((Gtk.IconSize)(3));
        this.hbox3.Add(this.toolbar4);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox3[this.toolbar4]));
        w3.Position = 0;
        // Container child hbox3.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar3'><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaPauseAction' action='mediaPauseAction'/><toolitem name='mediaStopAction' action='mediaStopAction'/><toolitem name='mediaPreviousAction' action='mediaPreviousAction'/><toolitem name='mediaNextAction' action='mediaNextAction'/></toolbar></ui>");
        this.toolbar3 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
        this.toolbar3.HeightRequest = 60;
        this.toolbar3.Name = "toolbar3";
        this.toolbar3.ShowArrow = false;
        this.toolbar3.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar3.IconSize = ((Gtk.IconSize)(3));
        this.hbox3.Add(this.toolbar3);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox3[this.toolbar3]));
        w4.Position = 1;
        w4.Expand = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar2'/></ui>");
        this.toolbar2 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
        this.toolbar2.Name = "toolbar2";
        this.toolbar2.ShowArrow = false;
        this.toolbar2.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar2.IconSize = ((Gtk.IconSize)(3));
        this.hbox3.Add(this.toolbar2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox3[this.toolbar2]));
        w5.Position = 2;
        this.vbox2.Add(this.hbox3);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        // Container child hbox4.Gtk.Box+BoxChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 4;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.countUpTimeLabel = new Gtk.Label();
        this.countUpTimeLabel.Name = "countUpTimeLabel";
        this.countUpTimeLabel.Xpad = 10;
        this.countUpTimeLabel.LabelProp = Mono.Unix.Catalog.GetString("00:00");
        this.countUpTimeLabel.SingleLineMode = true;
        this.hbox2.Add(this.countUpTimeLabel);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.countUpTimeLabel]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.vbox13 = new Gtk.VBox();
        this.vbox13.Name = "vbox13";
        this.vbox13.Spacing = 6;
        // Container child vbox13.Gtk.Box+BoxChild
        this.artistLabel = new Gtk.Label();
        this.artistLabel.Name = "artistLabel";
        this.artistLabel.Xpad = 10;
        this.artistLabel.LabelProp = Mono.Unix.Catalog.GetString("label4");
        this.artistLabel.Wrap = true;
        this.artistLabel.MaxWidthChars = 30;
        this.vbox13.Add(this.artistLabel);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox13[this.artistLabel]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox13.Gtk.Box+BoxChild
        this.trackLabel = new Gtk.Label();
        this.trackLabel.Name = "trackLabel";
        this.trackLabel.Xpad = 10;
        this.trackLabel.LabelProp = Mono.Unix.Catalog.GetString("label3");
        this.trackLabel.Wrap = true;
        this.vbox13.Add(this.trackLabel);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox13[this.trackLabel]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        // Container child vbox13.Gtk.Box+BoxChild
        this.albumLabel = new Gtk.Label();
        this.albumLabel.Name = "albumLabel";
        this.albumLabel.Xpad = 10;
        this.albumLabel.LabelProp = Mono.Unix.Catalog.GetString("label5");
        this.albumLabel.Wrap = true;
        this.vbox13.Add(this.albumLabel);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox13[this.albumLabel]));
        w10.Position = 2;
        w10.Expand = false;
        w10.Fill = false;
        this.hbox2.Add(this.vbox13);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox13]));
        w11.Position = 2;
        w11.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.countDownTimeLabel = new Gtk.Label();
        this.countDownTimeLabel.Name = "countDownTimeLabel";
        this.countDownTimeLabel.Xpad = 10;
        this.countDownTimeLabel.LabelProp = Mono.Unix.Catalog.GetString("00:00");
        this.countDownTimeLabel.Justify = ((Gtk.Justification)(1));
        this.countDownTimeLabel.SingleLineMode = true;
        this.hbox2.Add(this.countDownTimeLabel);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox2[this.countDownTimeLabel]));
        w12.PackType = ((Gtk.PackType)(1));
        w12.Position = 4;
        w12.Expand = false;
        w12.Fill = false;
        this.vbox3.Add(this.hbox2);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
        w13.Position = 0;
        w13.Padding = ((uint)(2));
        this.hbox5.Add(this.vbox3);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
        w14.Position = 0;
        this.vbox5.Add(this.hbox5);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        w15.Padding = ((uint)(2));
        this.hbox4.Add(this.vbox5);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox4[this.vbox5]));
        w16.Position = 0;
        w16.Padding = ((uint)(5));
        this.vbox2.Add(this.hbox4);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
        w17.Position = 2;
        w17.Expand = false;
        w17.Fill = false;
        w17.Padding = ((uint)(2));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.songProgressBar = new Gtk.HScale(null);
        this.songProgressBar.CanFocus = true;
        this.songProgressBar.Name = "songProgressBar";
        this.songProgressBar.Adjustment.Upper = 100;
        this.songProgressBar.Adjustment.PageIncrement = 10;
        this.songProgressBar.Adjustment.StepIncrement = 1;
        this.songProgressBar.DrawValue = false;
        this.songProgressBar.Digits = 0;
        this.songProgressBar.ValuePos = ((Gtk.PositionType)(2));
        this.hbox1.Add(this.songProgressBar);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox1[this.songProgressBar]));
        w18.Position = 0;
        w18.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox1);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
        w19.Position = 3;
        w19.Expand = false;
        w19.Fill = false;
        w19.Padding = ((uint)(2));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        // Container child hbox8.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 271;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.vpaned1 = new Gtk.VPaned();
        this.vpaned1.CanFocus = true;
        this.vpaned1.Name = "vpaned1";
        this.vpaned1.Position = 139;
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(2));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.nodeview2 = new Gtk.NodeView();
        this.nodeview2.CanFocus = true;
        this.nodeview2.Name = "nodeview2";
        this.GtkScrolledWindow1.Add(this.nodeview2);
        this.vpaned1.Add(this.GtkScrolledWindow1);
        Gtk.Paned.PanedChild w21 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.GtkScrolledWindow1]));
        w21.Resize = false;
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.GtkScrolledWindow2 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
        this.GtkScrolledWindow2.ShadowType = ((Gtk.ShadowType)(2));
        // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
        this.nodeview3 = new Gtk.NodeView();
        this.nodeview3.CanFocus = true;
        this.nodeview3.Name = "nodeview3";
        this.GtkScrolledWindow2.Add(this.nodeview3);
        this.vpaned1.Add(this.GtkScrolledWindow2);
        this.hpaned1.Add(this.vpaned1);
        Gtk.Paned.PanedChild w24 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vpaned1]));
        w24.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.hpaned2 = new Gtk.HPaned();
        this.hpaned2.CanFocus = true;
        this.hpaned2.Name = "hpaned2";
        this.hpaned2.Position = 465;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.WidthRequest = 600;
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(2));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.nodeview1 = new Gtk.NodeView();
        this.nodeview1.CanFocus = true;
        this.nodeview1.Name = "nodeview1";
        this.nodeview1.Reorderable = true;
        this.GtkScrolledWindow.Add(this.nodeview1);
        this.hpaned2.Add(this.GtkScrolledWindow);
        Gtk.Paned.PanedChild w26 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.GtkScrolledWindow]));
        w26.Resize = false;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.AlbumArtIcon = new Gtk.Image();
        this.AlbumArtIcon.Name = "AlbumArtIcon";
        this.vbox1.Add(this.AlbumArtIcon);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox1[this.AlbumArtIcon]));
        w27.Position = 0;
        w27.Expand = false;
        w27.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("label1");
        this.vbox1.Add(this.label1);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.label1]));
        w28.Position = 1;
        w28.Expand = false;
        w28.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("label2");
        this.vbox1.Add(this.label2);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox1[this.label2]));
        w29.Position = 2;
        w29.Expand = false;
        w29.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("label3");
        this.vbox1.Add(this.label3);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.vbox1[this.label3]));
        w30.Position = 3;
        w30.Expand = false;
        w30.Fill = false;
        this.hpaned2.Add(this.vbox1);
        this.hpaned1.Add(this.hpaned2);
        this.hbox8.Add(this.hpaned1);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox8[this.hpaned1]));
        w33.Position = 0;
        w33.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox8);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
        w34.Position = 4;
        w34.Padding = ((uint)(2));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox9 = new Gtk.HBox();
        this.hbox9.Name = "hbox9";
        this.hbox9.Spacing = 6;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vbox7 = new Gtk.VBox();
        this.vbox7.Name = "vbox7";
        this.vbox7.Spacing = 6;
        // Container child vbox7.Gtk.Box+BoxChild
        this.spacer2Label = new Gtk.Label();
        this.spacer2Label.Name = "spacer2Label";
        this.spacer2Label.LabelProp = Mono.Unix.Catalog.GetString("spacer");
        this.vbox7.Add(this.spacer2Label);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox7[this.spacer2Label]));
        w35.Position = 1;
        w35.Expand = false;
        w35.Fill = false;
        this.hbox9.Add(this.vbox7);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox9[this.vbox7]));
        w36.Position = 0;
        w36.Expand = false;
        w36.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale2 = new Gtk.VScale(null);
        this.vscale2.CanFocus = true;
        this.vscale2.Name = "vscale2";
        this.vscale2.Inverted = true;
        this.vscale2.Adjustment.Lower = -12;
        this.vscale2.Adjustment.Upper = 12;
        this.vscale2.Adjustment.PageIncrement = 10;
        this.vscale2.Adjustment.StepIncrement = 1;
        this.vscale2.DrawValue = false;
        this.vscale2.Digits = 0;
        this.vscale2.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale2);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale2]));
        w37.Position = 1;
        w37.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale3 = new Gtk.VScale(null);
        this.vscale3.CanFocus = true;
        this.vscale3.Name = "vscale3";
        this.vscale3.Inverted = true;
        this.vscale3.Adjustment.Lower = -12;
        this.vscale3.Adjustment.Upper = 12;
        this.vscale3.Adjustment.PageIncrement = 10;
        this.vscale3.Adjustment.StepIncrement = 1;
        this.vscale3.DrawValue = false;
        this.vscale3.Digits = 0;
        this.vscale3.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale3);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale3]));
        w38.Position = 2;
        w38.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale4 = new Gtk.VScale(null);
        this.vscale4.CanFocus = true;
        this.vscale4.Name = "vscale4";
        this.vscale4.Inverted = true;
        this.vscale4.Adjustment.Lower = -12;
        this.vscale4.Adjustment.Upper = 12;
        this.vscale4.Adjustment.PageIncrement = 10;
        this.vscale4.Adjustment.StepIncrement = 1;
        this.vscale4.DrawValue = false;
        this.vscale4.Digits = 0;
        this.vscale4.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale4);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale4]));
        w39.Position = 3;
        w39.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale5 = new Gtk.VScale(null);
        this.vscale5.CanFocus = true;
        this.vscale5.Name = "vscale5";
        this.vscale5.Inverted = true;
        this.vscale5.Adjustment.Lower = -12;
        this.vscale5.Adjustment.Upper = 12;
        this.vscale5.Adjustment.PageIncrement = 10;
        this.vscale5.Adjustment.StepIncrement = 1;
        this.vscale5.DrawValue = false;
        this.vscale5.Digits = 0;
        this.vscale5.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale5);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale5]));
        w40.Position = 4;
        w40.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale6 = new Gtk.VScale(null);
        this.vscale6.CanFocus = true;
        this.vscale6.Name = "vscale6";
        this.vscale6.Inverted = true;
        this.vscale6.Adjustment.Lower = -12;
        this.vscale6.Adjustment.Upper = 12;
        this.vscale6.Adjustment.PageIncrement = 10;
        this.vscale6.Adjustment.StepIncrement = 1;
        this.vscale6.DrawValue = false;
        this.vscale6.Digits = 0;
        this.vscale6.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale6);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale6]));
        w41.Position = 5;
        w41.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale7 = new Gtk.VScale(null);
        this.vscale7.CanFocus = true;
        this.vscale7.Name = "vscale7";
        this.vscale7.Inverted = true;
        this.vscale7.Adjustment.Lower = -12;
        this.vscale7.Adjustment.Upper = 12;
        this.vscale7.Adjustment.PageIncrement = 10;
        this.vscale7.Adjustment.StepIncrement = 1;
        this.vscale7.DrawValue = false;
        this.vscale7.Digits = 0;
        this.vscale7.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale7);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale7]));
        w42.Position = 6;
        w42.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale8 = new Gtk.VScale(null);
        this.vscale8.CanFocus = true;
        this.vscale8.Name = "vscale8";
        this.vscale8.Inverted = true;
        this.vscale8.Adjustment.Lower = -12;
        this.vscale8.Adjustment.Upper = 12;
        this.vscale8.Adjustment.PageIncrement = 10;
        this.vscale8.Adjustment.StepIncrement = 1;
        this.vscale8.DrawValue = false;
        this.vscale8.Digits = 0;
        this.vscale8.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale8);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale8]));
        w43.Position = 7;
        w43.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vscale9 = new Gtk.VScale(null);
        this.vscale9.CanFocus = true;
        this.vscale9.Name = "vscale9";
        this.vscale9.Inverted = true;
        this.vscale9.Adjustment.Lower = -12;
        this.vscale9.Adjustment.Upper = 12;
        this.vscale9.Adjustment.PageIncrement = 10;
        this.vscale9.Adjustment.StepIncrement = 10;
        this.vscale9.DrawValue = false;
        this.vscale9.Digits = 0;
        this.vscale9.ValuePos = ((Gtk.PositionType)(2));
        this.hbox9.Add(this.vscale9);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox9[this.vscale9]));
        w44.Position = 8;
        w44.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.vbox8 = new Gtk.VBox();
        this.vbox8.Name = "vbox8";
        this.vbox8.Spacing = 6;
        // Container child vbox8.Gtk.Box+BoxChild
        this.spacer1Label = new Gtk.Label();
        this.spacer1Label.Name = "spacer1Label";
        this.spacer1Label.LabelProp = Mono.Unix.Catalog.GetString("spacer");
        this.vbox8.Add(this.spacer1Label);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.vbox8[this.spacer1Label]));
        w45.Position = 1;
        w45.Expand = false;
        w45.Fill = false;
        this.hbox9.Add(this.vbox8);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.hbox9[this.vbox8]));
        w46.Position = 9;
        w46.Expand = false;
        w46.Fill = false;
        this.vbox2.Add(this.hbox9);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
        w47.Position = 5;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.newSongLabel = new Gtk.Label();
        this.newSongLabel.Name = "newSongLabel";
        this.newSongLabel.LabelProp = Mono.Unix.Catalog.GetString("label2");
        this.hbox7.Add(this.newSongLabel);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox7[this.newSongLabel]));
        w48.Position = 0;
        w48.Expand = false;
        w48.Fill = false;
        w48.Padding = ((uint)(6));
        this.vbox4.Add(this.hbox7);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
        w49.Position = 0;
        w49.Expand = false;
        w49.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.newSongLocationLabel = new Gtk.Label();
        this.newSongLocationLabel.Name = "newSongLocationLabel";
        this.newSongLocationLabel.LabelProp = Mono.Unix.Catalog.GetString("label3");
        this.hbox14.Add(this.newSongLocationLabel);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.hbox14[this.newSongLocationLabel]));
        w50.Position = 0;
        w50.Expand = false;
        w50.Fill = false;
        w50.Padding = ((uint)(6));
        // Container child hbox14.Gtk.Box+BoxChild
        this.tracksAddedLabel = new Gtk.Label();
        this.tracksAddedLabel.Name = "tracksAddedLabel";
        this.tracksAddedLabel.LabelProp = Mono.Unix.Catalog.GetString("label1");
        this.tracksAddedLabel.Justify = ((Gtk.Justification)(1));
        this.hbox14.Add(this.tracksAddedLabel);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.hbox14[this.tracksAddedLabel]));
        w51.PackType = ((Gtk.PackType)(1));
        w51.Position = 2;
        w51.Expand = false;
        w51.Fill = false;
        w51.Padding = ((uint)(6));
        this.vbox4.Add(this.hbox14);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox14]));
        w52.Position = 1;
        w52.Expand = false;
        w52.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.songsAddedProgressBar = new Gtk.ProgressBar();
        this.songsAddedProgressBar.HeightRequest = 12;
        this.songsAddedProgressBar.Name = "songsAddedProgressBar";
        this.hbox13.Add(this.songsAddedProgressBar);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.hbox13[this.songsAddedProgressBar]));
        w53.Position = 0;
        w53.Padding = ((uint)(6));
        this.vbox4.Add(this.hbox13);
        Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox13]));
        w54.Position = 2;
        w54.Expand = false;
        w54.Fill = false;
        this.hbox6.Add(this.vbox4);
        Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.hbox6[this.vbox4]));
        w55.Position = 0;
        // Container child hbox6.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.WidthRequest = 30;
        this.button1.HeightRequest = 30;
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Relief = ((Gtk.ReliefStyle)(2));
        // Container child button1.Gtk.Container+ContainerChild
        Gtk.Alignment w56 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w57 = new Gtk.HBox();
        w57.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w58 = new Gtk.Image();
        w58.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
        w57.Add(w58);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w60 = new Gtk.Label();
        w57.Add(w60);
        w56.Add(w57);
        this.button1.Add(w56);
        this.hbox6.Add(this.button1);
        Gtk.Box.BoxChild w64 = ((Gtk.Box.BoxChild)(this.hbox6[this.button1]));
        w64.PackType = ((Gtk.PackType)(1));
        w64.Position = 1;
        w64.Expand = false;
        w64.Fill = false;
        w64.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox6);
        Gtk.Box.BoxChild w65 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
        w65.Position = 6;
        w65.Expand = false;
        w65.Fill = false;
        w65.Padding = ((uint)(6));
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox10 = new Gtk.HBox();
        this.hbox10.Name = "hbox10";
        this.hbox10.Spacing = 6;
        // Container child hbox10.Gtk.Box+BoxChild
        this.vbox9 = new Gtk.VBox();
        this.vbox9.Name = "vbox9";
        this.vbox9.Spacing = 6;
        // Container child vbox9.Gtk.Box+BoxChild
        this.label19 = new Gtk.Label();
        this.label19.Name = "label19";
        this.label19.LabelProp = Mono.Unix.Catalog.GetString("Low");
        this.vbox9.Add(this.label19);
        Gtk.Box.BoxChild w66 = ((Gtk.Box.BoxChild)(this.vbox9[this.label19]));
        w66.Position = 0;
        w66.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.label17 = new Gtk.Label();
        this.label17.Name = "label17";
        this.label17.LabelProp = Mono.Unix.Catalog.GetString("Mid");
        this.vbox9.Add(this.label17);
        Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.vbox9[this.label17]));
        w67.Position = 1;
        w67.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.label18 = new Gtk.Label();
        this.label18.Name = "label18";
        this.label18.LabelProp = Mono.Unix.Catalog.GetString("High");
        this.vbox9.Add(this.label18);
        Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.vbox9[this.label18]));
        w68.Position = 2;
        w68.Fill = false;
        this.hbox10.Add(this.vbox9);
        Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.hbox10[this.vbox9]));
        w69.Position = 0;
        w69.Expand = false;
        w69.Fill = false;
        w69.Padding = ((uint)(6));
        // Container child hbox10.Gtk.Box+BoxChild
        this.vbox10 = new Gtk.VBox();
        this.vbox10.Name = "vbox10";
        this.vbox10.Spacing = 6;
        // Container child vbox10.Gtk.Box+BoxChild
        this.hscale2 = new Gtk.HScale(null);
        this.hscale2.CanFocus = true;
        this.hscale2.Name = "hscale2";
        this.hscale2.Adjustment.Upper = 3;
        this.hscale2.Adjustment.PageIncrement = 10;
        this.hscale2.Adjustment.StepIncrement = 0.1;
        this.hscale2.Adjustment.Value = 1;
        this.hscale2.DrawValue = false;
        this.hscale2.Digits = 0;
        this.hscale2.ValuePos = ((Gtk.PositionType)(2));
        this.vbox10.Add(this.hscale2);
        Gtk.Box.BoxChild w70 = ((Gtk.Box.BoxChild)(this.vbox10[this.hscale2]));
        w70.Position = 0;
        w70.Expand = false;
        w70.Fill = false;
        // Container child vbox10.Gtk.Box+BoxChild
        this.hscale3 = new Gtk.HScale(null);
        this.hscale3.CanFocus = true;
        this.hscale3.Name = "hscale3";
        this.hscale3.Adjustment.Upper = 3;
        this.hscale3.Adjustment.PageIncrement = 10;
        this.hscale3.Adjustment.StepIncrement = 0.1;
        this.hscale3.Adjustment.Value = 1;
        this.hscale3.DrawValue = false;
        this.hscale3.Digits = 0;
        this.hscale3.ValuePos = ((Gtk.PositionType)(2));
        this.vbox10.Add(this.hscale3);
        Gtk.Box.BoxChild w71 = ((Gtk.Box.BoxChild)(this.vbox10[this.hscale3]));
        w71.Position = 1;
        w71.Expand = false;
        w71.Fill = false;
        // Container child vbox10.Gtk.Box+BoxChild
        this.hscale4 = new Gtk.HScale(null);
        this.hscale4.CanFocus = true;
        this.hscale4.Name = "hscale4";
        this.hscale4.Adjustment.Upper = 3;
        this.hscale4.Adjustment.PageIncrement = 0.5;
        this.hscale4.Adjustment.StepIncrement = 0.1;
        this.hscale4.Adjustment.Value = 1;
        this.hscale4.DrawValue = false;
        this.hscale4.Digits = 0;
        this.hscale4.ValuePos = ((Gtk.PositionType)(2));
        this.vbox10.Add(this.hscale4);
        Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(this.vbox10[this.hscale4]));
        w72.Position = 2;
        w72.Expand = false;
        w72.Fill = false;
        this.hbox10.Add(this.vbox10);
        Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.hbox10[this.vbox10]));
        w73.Position = 1;
        w73.Padding = ((uint)(6));
        // Container child hbox10.Gtk.Box+BoxChild
        this.vbox11 = new Gtk.VBox();
        this.vbox11.Name = "vbox11";
        this.vbox11.Spacing = 6;
        // Container child vbox11.Gtk.Box+BoxChild
        this.hbox11 = new Gtk.HBox();
        this.hbox11.Name = "hbox11";
        this.hbox11.Spacing = 6;
        // Container child hbox11.Gtk.Box+BoxChild
        this.vbox12 = new Gtk.VBox();
        this.vbox12.Name = "vbox12";
        this.vbox12.Spacing = 6;
        // Container child vbox12.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.checkbutton2 = new Gtk.CheckButton();
        this.checkbutton2.CanFocus = true;
        this.checkbutton2.Name = "checkbutton2";
        this.checkbutton2.Label = Mono.Unix.Catalog.GetString("Enabled");
        this.checkbutton2.DrawIndicator = true;
        this.checkbutton2.UseUnderline = true;
        this.hbox12.Add(this.checkbutton2);
        Gtk.Box.BoxChild w74 = ((Gtk.Box.BoxChild)(this.hbox12[this.checkbutton2]));
        w74.Position = 0;
        w74.Expand = false;
        w74.Padding = ((uint)(6));
        this.vbox12.Add(this.hbox12);
        Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(this.vbox12[this.hbox12]));
        w75.Position = 1;
        w75.Expand = false;
        w75.Fill = false;
        this.hbox11.Add(this.vbox12);
        Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(this.hbox11[this.vbox12]));
        w76.PackType = ((Gtk.PackType)(1));
        w76.Position = 0;
        this.vbox11.Add(this.hbox11);
        Gtk.Box.BoxChild w77 = ((Gtk.Box.BoxChild)(this.vbox11[this.hbox11]));
        w77.Position = 0;
        this.hbox10.Add(this.vbox11);
        Gtk.Box.BoxChild w78 = ((Gtk.Box.BoxChild)(this.hbox10[this.vbox11]));
        w78.Position = 2;
        w78.Expand = false;
        w78.Fill = false;
        this.vbox2.Add(this.hbox10);
        Gtk.Box.BoxChild w79 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox10]));
        w79.Position = 7;
        w79.Expand = false;
        w79.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='addMediaButton' action='addMediaButton'/><toolitem name='removeAction' action='removeAction'/><toolitem name='clearAction' action='clearAction'/><toolitem name='stockPlaylistAction' action='stockPlaylistAction'/><toolitem name='stockVolumeAction1' action='stockVolumeAction1'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar1.IconSize = ((Gtk.IconSize)(1));
        this.vbox2.Add(this.toolbar1);
        Gtk.Box.BoxChild w80 = ((Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
        w80.Position = 8;
        w80.Expand = false;
        w80.Fill = false;
        this.Add(this.vbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 978;
        this.DefaultHeight = 845;
        this.hbox4.Hide();
        this.hbox9.Hide();
        this.hbox10.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.MainWindowFocusChangedButtonReleaseHandler);
        this.mediaPreviousAction.Activated += new System.EventHandler(this.OnMediaPreviousActionActivated);
        this.mediaNextAction.Activated += new System.EventHandler(this.OnMediaNextActionActivated);
        this.mediaPlayAction.Activated += new System.EventHandler(this.OnMediaPlayActionActivated);
        this.mediaStopAction.Activated += new System.EventHandler(this.OnMediaStopActionActivated);
        this.mediaPauseAction.Activated += new System.EventHandler(this.OnMediaPauseActionActivated);
        this.clearAction.Activated += new System.EventHandler(this.OnClearActionActivated);
        this.stockPlaylistAction.Toggled += new System.EventHandler(this.OnAudioSettingsActionToggled);
        this.stockVolumeAction1.Activated += new System.EventHandler(this.VolumeButtonActivatedHandler);
        this.songProgressBar.ChangeValue += new Gtk.ChangeValueHandler(this.OnHscale1ChangeValue);
        this.nodeview1.RowActivated += new Gtk.RowActivatedHandler(this.OnNodeview1RowActivated);
        this.nodeview1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.MusicNodeViewSelectionHandler);
        this.vscale2.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale2ChangeValue);
        this.vscale3.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale3ChangeValue);
        this.vscale4.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale4ChangeValue);
        this.vscale5.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale5ChangeValue);
        this.vscale6.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale6ChangeValue);
        this.vscale7.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale7ChangeValue);
        this.vscale8.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale8ChangeValue);
        this.vscale9.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscale9ChangeValue);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.hscale2.ValueChanged += new System.EventHandler(this.simpleEqualizerValueChanged);
        this.hscale3.ValueChanged += new System.EventHandler(this.simpleEqualizerValueChanged);
        this.hscale4.ValueChanged += new System.EventHandler(this.simpleEqualizerValueChanged);
        this.checkbutton2.Toggled += new System.EventHandler(this.OnCheckbutton2Toggled);
    }
}
